return {
	-- Spline parameters
	DEFAULT_ALPHA = 0.5,
	DEFAULT_TENSION = 0,

	-- Numerical method tunings
	DEFAULT_ARC_LENGTH_CHEB_DEGREE = 8,
	DEFAULT_RMF_PRECOMPUTES = 4,
	MAX_NEWTON_ITERATIONS = 16,
	MAX_REGULA_FALSI_ITERATIONS = 10,

	-- Tolerances
	MACHINE_EPSILON = 2e-7,
	SOLVE_TOLERANCE = 1e-4,
	SQUAD_TOLERANCE = 1e-4,
}